export const rtkQueryTags = {
  CART: "CART",
  USER_ORDERS: "USER_ORDERS",
  ADMIN_ORDERS: "ADMIN_ORDERS",
  ADMIN_PRODUCTS: "ADMIN_PRODUCTS",
  PRODUCTS: "PRODUCTS",
  BESTSELLERS: "BESTSELLERS",
  SALES: "SALES",
  ARTICLES: "ARTICLES",
  SUGGESTED_PRODUCT: "SUGGESTED_PRODUCT",
  USER_PROFILE: "USER_PROFILE",
  VIEW_HISTORY: "VIEW_HISTORY",
  WISHLIST: "WISHLIST",
  ADDRESSES: "ADDRESSES",,
  USER_PHOTO: "USER_PHOTO",
} as const;

export const rtkQueryTagsArray = Object.values(rtkQueryTags);
